// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/movie.proto

package moviepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRequest) Reset() {
	*x = MovieRequest{}
	mi := &file_internal_proto_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRequest) ProtoMessage() {}

func (x *MovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRequest.ProtoReflect.Descriptor instead.
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *MovieRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type MovieId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       uint64                 `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieId) Reset() {
	*x = MovieId{}
	mi := &file_internal_proto_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieId) ProtoMessage() {}

func (x *MovieId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieId.ProtoReflect.Descriptor instead.
func (*MovieId) Descriptor() ([]byte, []int) {
	return file_internal_proto_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieId) GetMovieId() uint64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieData     *MovieRequest          `protobuf:"bytes,1,opt,name=movieData,proto3" json:"movieData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_internal_proto_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_movie_proto_rawDescGZIP(), []int{2}
}

func (x *MovieResponse) GetMovieData() *MovieRequest {
	if x != nil {
		return x.MovieData
	}
	return nil
}

var File_internal_proto_movie_proto protoreflect.FileDescriptor

const file_internal_proto_movie_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/movie.proto\x12\amoviepb\"Z\n" +
	"\fMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\"#\n" +
	"\aMovieId\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\x04R\amovieId\"D\n" +
	"\rMovieResponse\x123\n" +
	"\tmovieData\x18\x01 \x01(\v2\x15.moviepb.MovieRequestR\tmovieData2D\n" +
	"\fMovieService\x124\n" +
	"\bGetMovie\x12\x10.moviepb.MovieId\x1a\x16.moviepb.MovieResponseB\x1aZ\x18./internal/proto/moviepbb\x06proto3"

var (
	file_internal_proto_movie_proto_rawDescOnce sync.Once
	file_internal_proto_movie_proto_rawDescData []byte
)

func file_internal_proto_movie_proto_rawDescGZIP() []byte {
	file_internal_proto_movie_proto_rawDescOnce.Do(func() {
		file_internal_proto_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_movie_proto_rawDesc), len(file_internal_proto_movie_proto_rawDesc)))
	})
	return file_internal_proto_movie_proto_rawDescData
}

var file_internal_proto_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_movie_proto_goTypes = []any{
	(*MovieRequest)(nil),  // 0: moviepb.MovieRequest
	(*MovieId)(nil),       // 1: moviepb.MovieId
	(*MovieResponse)(nil), // 2: moviepb.MovieResponse
}
var file_internal_proto_movie_proto_depIdxs = []int32{
	0, // 0: moviepb.MovieResponse.movieData:type_name -> moviepb.MovieRequest
	1, // 1: moviepb.MovieService.GetMovie:input_type -> moviepb.MovieId
	2, // 2: moviepb.MovieService.GetMovie:output_type -> moviepb.MovieResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_movie_proto_init() }
func file_internal_proto_movie_proto_init() {
	if File_internal_proto_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_movie_proto_rawDesc), len(file_internal_proto_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_movie_proto_goTypes,
		DependencyIndexes: file_internal_proto_movie_proto_depIdxs,
		MessageInfos:      file_internal_proto_movie_proto_msgTypes,
	}.Build()
	File_internal_proto_movie_proto = out.File
	file_internal_proto_movie_proto_goTypes = nil
	file_internal_proto_movie_proto_depIdxs = nil
}
